"use client";

import { formatCompactNumber } from "@/lib/format";
import { ProductResponse } from "@/services/productService";

interface StockOpnamePrintTableProps {
  data: ProductResponse[];
  searchTerm?: string;
  printDate?: string;
}

export function StockOpnamePrintTable({
  data,
  searchTerm,
  printDate,
}: StockOpnamePrintTableProps) {
  return (
    <div
      id="stock-opname-print-area"
      className="hidden print:block p-6 font-sans text-black"
    >
      <div className="mb-8 text-center">
        <h1 className="text-3xl font-bold uppercase tracking-widest mb-1">
          LAPORAN STOK OPNAME
        </h1>
        <p className="text-sm text-gray-600">
          Dicetak pada: {printDate || new Date().toLocaleString("id-ID")}
        </p>
        {searchTerm && (
          <p className="text-xs mt-1 text-gray-500">
            Filter pencarian: &quot;{searchTerm}&quot;
          </p>
        )}
      </div>

      <table className="w-full border-collapse print-table">
        <thead>
          <tr className="bg-gray-100">
            <th className="border border-black p-3 text-center w-12">No</th>
            <th className="border border-black p-3 text-left">Produk & SKU</th>
            <th className="border border-black p-3 text-left">Variant</th>
            <th className="border border-black p-3 text-center">
              Stok Base Unit
            </th>
            <th className="border border-black p-3 text-center">Satuan</th>
            <th className="border border-black p-3 text-center w-32">
              Stok Aktual
            </th>
            <th className="border border-black p-3 text-left">Keterangan</th>
          </tr>
        </thead>
        <tbody>
          {data.flatMap((product, productIdx) => {
            if (product.variants && product.variants.length > 0) {
              return product.variants.map((variant, variantIdx) => (
                <tr key={`${product.id}-${variant.id}`}>
                  <td className="border border-black p-3 text-center">
                    {productIdx + 1}.{variantIdx + 1}
                  </td>
                  <td className="border border-black p-3">
                    <div className="font-medium">{product.name}</div>
                    <div className="text-[11px] text-gray-700">
                      {product.sku}
                    </div>
                  </td>
                  <td className="border border-black p-3 font-mono text-xs">
                    {variant.name}
                  </td>
                  <td className="border border-black p-3 text-center">
                    {formatCompactNumber(product.stock || 0)}{" "}
                    {product.unit?.name || ""}
                  </td>
                  <td className="border border-black p-3 text-center text-xs">
                    {variant.unit?.name || "-"}
                  </td>
                  <td className="border border-black p-3"></td>
                  <td className="border border-black p-3"></td>
                </tr>
              ));
            }

            return (
              <tr key={product.id}>
                <td className="border border-black p-3 text-center">
                  {productIdx + 1}
                </td>
                <td className="border border-black p-3">
                  <div className="font-medium">{product.name}</div>
                  <div className="text-[11px] text-gray-700">{product.sku}</div>
                </td>
                <td className="border border-black p-3 text-xs">-</td>
                <td className="border border-black p-3 text-center">
                  {formatCompactNumber(product.stock || 0)}{" "}
                  {product.unit?.name || ""}
                </td>
                <td className="border border-black p-3 text-center text-xs">
                  {product.unit?.name || "-"}
                </td>
                <td className="border border-black p-3"></td>
                <td className="border border-black p-3"></td>
              </tr>
            );
          })}
        </tbody>
      </table>

      <div className="mt-12 pt-4 border-t border-dashed text-xs text-gray-500 flex justify-between">
        <div>Generated by Sistem Inventori</div>
        <div>
          Halaman <span className="print-page-number"></span>
        </div>
      </div>
    </div>
  );
}
