@startuml Return_Process_Sequence
autonumber

skinparam BoxPadding 10
skinparam ParticipantPadding 10
skinparam defaultFontSize 20
skinparam maxMessageSize 300

actor "Admin / Kasir" as Admin
boundary "UI Retur" as UI
control "Return Controller" as Controller
database "DB" as DB

== 1. Validasi & Pengecekan Nota ==
Admin -> UI : Masukkan nomor nota & barang retur
UI -> Controller : Proses permintaan retur pelanggan
activate Controller
Controller -> DB : Validasi nomor nota & riwayat pembelian
DB --> Controller : Data valid

== 2. Penanganan Fisik & Stok ==
alt Status Barang: Layak Jual
    Controller -> DB : Kembalikan stok produk & simpan mutasi
else Status Barang: Rusak
    note right: Stok tidak dikembalikan ke inventori aktif
end

== 3. Kompensasi & Finalisasi ==
alt Kompensasi: Tunai / Saldo
    Controller -> DB : Perbarui saldo pelanggan atau penyiapan dana
else Kompensasi: Tukar Barang
    Controller -> DB : Validasi stok & kurangi barang pengganti
end

Controller -> DB : Simpan rincian data retur
Controller --> UI : Konfirmasi Berhasil (Tampilkan Nota Retur)
deactivate Controller
@enduml