@startuml Return_Process_Sequence
autonumber

skinparam BoxPadding 5
skinparam ParticipantPadding 8
skinparam defaultFontSize 12
skinparam maxMessageSize 140
skinparam sequenceMessageAlign center

actor "Admin Sistem /\nAdmin Toko" as Admin
boundary "UI Retur" as UI
control "Return Controller" as Ctrl
database "sales" as s
database "products" as p
database "customer_returns" as cr
database "return_items" as ri
database "stock_mutations" as sm
box "Kompensasi" #F5F5F5
    database "customers" as c
    database "balance_mutations" as bm
end box

== 1. Validasi Nota ==
Admin -> UI : Input nota & pilih barang retur
UI -> Ctrl : Proses retur
activate Ctrl
Ctrl -> s : Fetch penjualan asli\n(+ items, retur lama)
note right: Validasi: item ada di invoice, qty tidak melebihi sisa

== 2. Penanganan Stok ==
alt Barang Layak Jual (returnedToStock = true)
    Ctrl -> p : UPDATE stok\n(tambah qty × conversion)
    Ctrl -> sm : Insert stock_mutations\n(return_restock)
else Barang Rusak
    note right: Stok tidak dikembalikan
end

== 3. Kompensasi ==
alt Refund (Tunai)
    
else Credit Note (Saldo)
    Ctrl -> c : UPDATE creditBalance\n(tambah totalRefund)
    Ctrl -> bm : Insert balance_mut.\n(return_deposit)
end

== 4. Simpan Data Retur ==
Ctrl -> cr : Insert customer_returns\n(number, total, type)
Ctrl -> ri : Insert return_items\n(qty, price, reason)

Ctrl --> UI : Konfirmasi (tampilkan nota retur)
deactivate Ctrl


@enduml
