@startuml POS_System_Use_Case
top to bottom direction
skinparam packageStyle rectangle
skinparam shadowing false
skinparam monochrome true
skinparam defaultFontName "Arial"

actor "Admin Toko" as StoreAdmin
actor "Admin Sistem" as SystemAdmin

' Admin Sistem memiliki semua hak akses Admin Toko + hak manajerial
StoreAdmin <|-- SystemAdmin

rectangle "Modul Sistem POS" {
    
    package "Modul A: Pengelolaan Produk" {
        usecase "Kelola Produk & Kategori" as UC_Product
    }

    package "Modul B: Pengelolaan Pembelian" {
        usecase "Kelola Pembelian & Supplier" as UC_Purchase
    }

    package "Modul C: Penyelarasan Stok" {
        usecase "Lakukan Stok Opname / Penyesuaian" as UC_Stock
    }

    package "Modul D: Kasir / Penjualan" {
        usecase "Proses Transaksi Penjualan" as UC_Sale
    }

    package "Modul E: Retur Pelanggan" {
        usecase "Proses Retur Pelanggan" as UC_Return
    }

    package "Modul F: Pembayaran Piutang" {
        usecase "Kelola Piutang Pelanggan" as UC_Debt
    }

    package "Modul G: Laporan & Keuangan" {
        usecase "Lihat Laporan Keuangan" as UC_Report
        usecase "Konfigurasi Biaya Operasional & Pajak" as UC_Finance
    }

    package "Modul H: Pengelolaan Sampah Data" {
        usecase "Pulihkan / Hapus Permanen Data" as UC_Trash
    }

    package "Modul I: Pengelolaan Pengguna" {
        usecase "Kelola Pengguna Sistem" as UC_User
    }
}

' Hak Akses Admin Toko (Operasional Garis Depan)
StoreAdmin --> UC_Sale
StoreAdmin --> UC_Return
StoreAdmin --> UC_Debt

' Hak Akses Admin Sistem (Manajerial & Back-office)
SystemAdmin --> UC_Product
SystemAdmin --> UC_Purchase
SystemAdmin --> UC_Stock
SystemAdmin --> UC_Report
SystemAdmin --> UC_Finance
SystemAdmin --> UC_Trash
SystemAdmin --> UC_User

' Ketergantungan Fungsional
UC_Sale ..> UC_Stock : <<include>> Update Stok
UC_Purchase ..> UC_Stock : <<include>> Update Stok
UC_Return ..> UC_Sale : <<extend>> Validasi Nota
UC_Purchase ..> UC_Product : <<include>> Update HPP
UC_Debt ..> UC_Sale : <<extend>> Dipicu Penjualan Kredit
UC_Report ..> UC_Sale : <<include>> Agregasi Data
UC_Report ..> UC_Purchase : <<include>> Agregasi Data
UC_Trash ..> UC_Product : <<extend>> Arsip/Pulihkan

@enduml
