@startuml
|Admin Toko|
start
:Buka menu Tagihan Pelanggan;
:Lihat daftar piutang aktif;
:Pilih identitas pelanggan dan tentukan nominal bayar;

|Sistem POS|
:Verifikasi nominal bayar terhadap sisa tagihan;
if (Nominal Valid?) then (Ya)
  :Kurangi sisa tagihan pada sistem;
  if (Tagihan Selesai?) then (Ya)
    :Ubah status menjadi "Lunas";
  else (Belum Selesai)
    :Ubah status menjadi "Lunas Sebagian";
  endif
  :Catat peristiwa pembayaran tagihan;
  |Admin Toko|
  :Berikan bukti pembayaran kepada pelanggan;
else (Tidak)
  |Sistem POS|
  :Berikan informasi kesalahan nominal;
endif
stop
@enduml
