@startuml
|Admin Toko|
start
:Buka menu Pengadaan (Purchase);
:Pilih Pemasok (Supplier) dan daftar barang;
:Masukkan jumlah dan harga pengadaan;
:Simpan transaksi pengadaan;

|Sistem POS|
:Cek konsistensi data barang dalam daftar;
if (Data Konsisten?) then (Ya)
  :Buat identitas transaksi pengadaan;
  :Otomasi perhitungan total nilai barang;
  :Tambah jumlah produk ke sistem gudang;
  :Kalkulasi ulang nilai pokok barang (HPP);
  :Catat pembaharuan data histori stok;
  |Admin Toko|
  :Konfirmasi pengadaan berhasil direkam;
else (Tidak)
  |Sistem POS|
  :Berikan informasi kendala pada data;
endif
stop
@enduml
