@startuml
autonumber

skinparam BoxPadding 10
skinparam ParticipantPadding 10
skinparam defaultFontSize 20
skinparam maxMessageSize 400

actor "Admin Sistem" as Admin
boundary "UI Kelola Pengguna" as UI
control "User Controller" as Controller
database "DB" as DB

== 1. Pengelolaan Data Pengguna ==
Admin -> UI : Pilih Aksi (Tambah / Edit / Hapus)

alt Aksi: Tambah User
    Admin -> UI : Input data & password
    UI -> Controller : Kirim data pengguna baru
    Controller -> Controller : Hash Password & Validasi
    Controller -> DB : Simpan data pengguna & role
else Aksi: Edit User
    Admin -> UI : Ubah data / password
    UI -> Controller : Kirim pembaruan data pengguna
    Controller -> DB : Perbarui data pengguna
else Aksi: Hapus User
    Admin -> UI : Klik Hapus
    UI -> Controller : Request hapus pengguna
    Controller -> DB : Hapus data pengguna
end

Controller --> UI : Konfirmasi Berhasil
UI --> Admin : Refresh list pengguna
@enduml