@startuml
|Admin Toko / Admin Sistem|
start
:Buka menu Produk;
:Pilih aksi (Tambah, Edit, atau Hapus);

if (Aksi?) then (Tambah Produk)
  :Input identitas produk, kategori, dan daftar varian;
  :Lengkapi data harga dan konversi satuan tiap varian;
  |Sistem POS|
  :Validasi kelengkapan dan format data;
  if (Data Valid?) then (Ya)
    :Rekam data produk baru;
  else (Tidak)
    :Berikan pemberitahuan kesalahan data;
    stop
  endif

else if (Edit Produk)
  |Admin Toko / Admin Sistem|
  :Sesuaikan data produk atau susunan varian;
  |Sistem POS|
  :Verifikasi perubahan data;
  if (Data Valid?) then (Ya)
    :Simpan pembaharuan data;
  else (Tidak)
    :Berikan pemberitahuan kesalahan;
    stop
  endif

else (Hapus Produk)
  |Admin Toko / Admin Sistem|
  :Pilih produk yang akan dinonaktifkan;
  |Sistem POS|
  :Pindahkan produk ke dalam folder Sampah/Arsip;
endif

|Sistem POS|
:Tampilkan notifikasi keberhasilan transaksi;
|Admin Toko / Admin Sistem|
:Konfirmasi perubahan pada daftar produk;
stop
@enduml
