@startuml
|Admin Toko|
start
:Buka menu Retur Pelanggan;
:Tarik data transaksi awal;
:Tentukan barang yang dikembalikan dan jumlahnya;
:Tentukan status kondisi fisik barang;
:Pilih solusi kompensasi (Refun / Saldo / Tukar);

|Sistem POS|
:Validasi keberadaan data transaksi awal;
:Cek sisa barang yang dapat diretur;
if (Validasi Lolos?) then (Ya)
  if (Barang masih bernilai jual?) then (Ya)
    :Kembalikan stok ke sistem gudang;
    :Catat arus masuk barang (retur);
  else (Tidak)
    :Data stok tidak berubah (barang afkir);
  endif

  if (Bentuk Kompensasi?) then (Kembali Dana / Refund)
    :Hitung nilai pengembalian dana;
    :Berikan dana sesuai perhitungan;
  else if (Kredit Saldo)
    :Tambahkan nilai ke saldo pelanggan;
  else (Tukar Barang)
    :Verifikasi ketersediaan barang pengganti;
    :Kurangi stok barang pengganti;
    :Kalkulasi selisih nilai transaksi;
    if (Dana Berlebih?) then (Ya)
      :Kembalikan sisa dana ke pelanggan;
    else if (Dana Kurang?) then (Ya)
      :Tagih selisih ke pelanggan;
    else (Impas)
    endif
  endif
  :Simpan rincian data retur;
  |Admin Toko|
  :Berikan bukti retur kepada pelanggan;
else (Tidak)
  |Sistem POS|
  :Berikan informasi kendala data retur;
endif
stop
@enduml
